import localFont from "next/font/local";
import Header from "../components/Header/Header";
import { products } from "../data/products.js";
import "./globals.css";

const montserrat = localFont({
    src: [
        {
            path: "../../public/fonts/Montserrat-SemiBold.ttf",
            weight: "400",
            style: "normal",
        },
    ],
    variable: "--font-montserrat",
    display: "swap",
});

export const metadata = {
  title: "Eletronics Store - JSX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={montserrat.variable}>
        <Header
          title="🛒 Loja de Eletrônicos"
          subtitle="Os melhores produtos com os melhores preços!"
          totalProducts={`📊 Total de produtos: ${products.length}`}
        />
        {children}
      </body>
    </html>
  );
}
